int _main(void);
int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int n);
int print_last_digit(int n);
void jack_bauer(void);
void times_table(void);
int add(int n, int m);
void print_to_98(int n);
void print_number(int n);
int ln(int n);
int base_ten(int k);
void print_times_table(int n);
void print_num(int n);
void print_comaspace(int n);
void sum_3_5(void);
